/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MemorialRouteImport } from './routes/memorial'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KingsRouteImport } from './routes/kings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialRoute = MemorialRouteImport.update({
  id: '/memorial',
  path: '/memorial',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KingsRoute = KingsRouteImport.update({
  id: '/kings',
  path: '/kings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/history': typeof HistoryRoute
  '/kings': typeof KingsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/memorial': typeof MemorialRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/history': typeof HistoryRoute
  '/kings': typeof KingsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/memorial': typeof MemorialRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/history': typeof HistoryRoute
  '/kings': typeof KingsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/memorial': typeof MemorialRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/history'
    | '/kings'
    | '/login'
    | '/map'
    | '/memorial'
    | '/news'
    | '/signup'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/history'
    | '/kings'
    | '/login'
    | '/map'
    | '/memorial'
    | '/news'
    | '/signup'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/history'
    | '/kings'
    | '/login'
    | '/map'
    | '/memorial'
    | '/news'
    | '/signup'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  HistoryRoute: typeof HistoryRoute
  KingsRoute: typeof KingsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MemorialRoute: typeof MemorialRoute
  NewsRoute: typeof NewsRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial': {
      id: '/memorial'
      path: '/memorial'
      fullPath: '/memorial'
      preLoaderRoute: typeof MemorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kings': {
      id: '/kings'
      path: '/kings'
      fullPath: '/kings'
      preLoaderRoute: typeof KingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  HistoryRoute: HistoryRoute,
  KingsRoute: KingsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MemorialRoute: MemorialRoute,
  NewsRoute: NewsRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
